[package]
name = "yew-state"
version = "0.2.0"
authors = ["Noah <noah@coronasoftware.net>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/intendednull/yew-state"
readme = "README.md"
description = "Ergonomic shared state for Yew"
keywords = ["yew", "state", "session", "storage", "shared"]
categories = ["wasm", "web-programming", "api-bindings", "rust-patterns"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.114", features = ["rc"] }
yew = "^0.17"
