[package]
name = "yewdux-input"
version = "0.1.0"
edition = "2018"

[dependencies]
yew = { git = "https://github.com/yewstack/yew.git" }
yewdux = { path = "../yewdux" }
js-sys = "0.3.50"
gloo = "0.2.1"
web-sys = "0.3.55"
